name: go vet test

on:
  pull_request:
  push:

jobs:
  statictest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          mkdir -p $GITHUB_WORKSPACE/.tools
          chmod +x $GITHUB_WORKSPACE/.tools/statictest
          sudo mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
